from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from services.agent_runtime.thin_bootstrap_sandbox import run_cheapest_sandbox

SCHEMA_VERSION = "xinao.codex_s.thin_bootstrap_runner.v1"
SENTINEL = "SENTINEL:XINAO_THIN_BOOTSTRAP_RUNNER_READY"
DEFAULT_RUNTIME = Path(r"D:\XINAO_RESEARCH_RUNTIME")
DEFAULT_REPO = Path(os.environ.get("XINAO_CODEX_S_REPO_ROOT", r"E:\XINAO_RESEARCH_WORKSPACES\S"))


def _now_iso() -> str:
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + f".{os.getpid()}.tmp")
    tmp.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    os.replace(tmp, path)


def intake_markdown(input_path: Path) -> dict[str, Any]:
    from markitdown import MarkItDown

    result = MarkItDown().convert(str(input_path))
    text = (result.text_content or "")[:4000]
    return {
        "source": str(input_path),
        "content_md": text,
        "timestamp": _now_iso(),
    }


def apply_workspace_proof(repo_root: Path, sandbox_stdout: str, run_id: str) -> Path:
    proof = repo_root / "services" / "agent_runtime" / "thin_bootstrap_proof.py"
    proof.parent.mkdir(parents=True, exist_ok=True)
    proof.write_text(
        "\n".join(
            [
                '"""Auto-generated by thin_bootstrap_runner; do not hand-edit."""',
                "",
                f"RUN_ID = {run_id!r}",
                "",
                "def hello() -> str:",
                '    return "bootstrap_ok"',
                "",
                f"SANDBOX_PREVIEW = {sandbox_stdout[:500]!r}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return proof


def git_commit_all(repo_root: Path, message: str) -> dict[str, Any]:
    try:
        import git
    except ImportError:
        import subprocess

        subprocess.run(["git", "add", "-A"], cwd=repo_root, check=False, capture_output=True)
        proc = subprocess.run(
            ["git", "commit", "-m", message],
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=False,
        )
        head = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=False,
        )
        return {
            "commit_hash": (head.stdout or "").strip(),
            "commit_message": message,
            "created_new": proc.returncode == 0,
            "adapter": "git_cli_fallback",
        }

    repo = git.Repo(repo_root)
    repo.git.add(all=True)
    if not repo.is_dirty(untracked_files=True):
        head = repo.head.commit
        return {
            "commit_hash": head.hexsha,
            "commit_message": head.message.strip(),
            "created_new": False,
            "adapter": "gitpython",
        }
    commit = repo.index.commit(message)
    return {
        "commit_hash": commit.hexsha,
        "commit_message": commit.message.strip(),
        "created_new": True,
        "adapter": "gitpython",
    }


def run_thin_bootstrap(
    input_path: Path,
    *,
    runtime_root: Path = DEFAULT_RUNTIME,
    repo_root: Path = DEFAULT_REPO,
    prefer_e2b: bool = False,
    prefer_docker: bool = True,
) -> dict[str, Any]:
    run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    task_package = intake_markdown(input_path)
    preview = (task_package.get("content_md") or "")[:240]
    preview_literal = json.dumps(preview, ensure_ascii=False)
    sandbox_code = (
        "from datetime import datetime\n"
        "print('thin_bootstrap executed', datetime.now().isoformat())\n"
        f"print('task_preview', {preview_literal})\n"
        "print('status=ok')\n"
    )
    sandbox = run_cheapest_sandbox(
        sandbox_code, prefer_e2b=prefer_e2b, prefer_docker=prefer_docker
    )
    if sandbox.exit_code != 0:
        raise RuntimeError(f"sandbox failed: {sandbox.stderr or sandbox.stdout}")

    proof_path = apply_workspace_proof(repo_root, sandbox.stdout, run_id)
    commit_info = git_commit_all(repo_root, f"thin_bootstrap: {run_id}")

    evidence = {
        "schema_version": SCHEMA_VERSION,
        "sentinel": SENTINEL,
        "run_id": run_id,
        "phase": "thin_bootstrap_v1",
        "not_333_mainline": True,
        "intake": task_package,
        "sandbox": {
            "backend": sandbox.backend,
            "stdout": sandbox.stdout,
            "stderr": sandbox.stderr,
            "exit_code": sandbox.exit_code,
        },
        "workspace_proof": str(proof_path),
        "git": commit_info,
        "acceptance_now_can_invoke_cn": (
            "最小自举已跑通：桌面材料→markitdown→本地沙箱→S仓落盘→git commit→D盘证据。"
        ),
        "verification_due": "2026-07-09",
        "timestamp": _now_iso(),
    }

    evidence_dir = runtime_root / "readback"
    closure_dir = runtime_root / "closure" / run_id
    bootstrap_dir = runtime_root / "bootstrap"
    evidence_path = evidence_dir / f"thin_bootstrap_{run_id}.json"
    manifest_path = closure_dir / "closure_manifest.json"
    pending_path = bootstrap_dir / "acceptance_pending.json"

    _write_json(evidence_path, evidence)
    _write_json(
        manifest_path,
        {
            "run_id": run_id,
            "status": "bootstrap_smoke_passed",
            "git_commit_hash": commit_info["commit_hash"],
            "pytest_passed": None,
            "sandbox_backend": sandbox.backend,
            "evidence_path": str(evidence_path),
            "acceptance_now_can_invoke_cn": evidence["acceptance_now_can_invoke_cn"],
            "named_blocker": None,
        },
    )
    _write_json(
        pending_path,
        {
            "schema_version": "xinao.bootstrap.acceptance_pending.v1",
            "due_date": "2026-07-09",
            "run_id": run_id,
            "checks": [
                f"Test-Path {evidence_path}",
                f"Test-Path {manifest_path}",
                f"git -C {repo_root} log -1 --oneline",
                f"Test-Path {proof_path}",
            ],
            "evidence_path": str(evidence_path),
            "manifest_path": str(manifest_path),
        },
    )

    zh_path = evidence_dir / "zh" / f"thin_bootstrap_{run_id}.md"
    zh_path.parent.mkdir(parents=True, exist_ok=True)
    zh_path.write_text(
        "\n".join(
            [
                f"# 薄自举 readback {run_id}",
                "",
                f"- 沙箱：{sandbox.backend}",
                f"- commit：{commit_info['commit_hash'][:12]}",
                f"- 新文件：{proof_path.name}",
                f"- 现在能干什么：{evidence['acceptance_now_can_invoke_cn']}",
                "",
                "明天验收：看 D 盘 evidence + git log + 本文件是否仍在。",
            ]
        ),
        encoding="utf-8",
    )
    evidence["readback_zh"] = str(zh_path)
    evidence["closure_manifest"] = str(manifest_path)
    _write_json(evidence_path, evidence)
    return evidence


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="XINAO thin bootstrap runner (cheap local sandbox)")
    parser.add_argument(
        "--input",
        default=str(DEFAULT_REPO / "materials" / "thin_bootstrap_input.md"),
        help="Material intake markdown path",
    )
    parser.add_argument("--prefer-e2b", action="store_true")
    parser.add_argument("--no-docker", action="store_true")
    args = parser.parse_args(argv)
    input_path = Path(args.input)
    if not input_path.is_file():
        print(f"input missing: {input_path}", file=sys.stderr)
        return 2
    payload = run_thin_bootstrap(
        input_path, prefer_e2b=args.prefer_e2b, prefer_docker=not args.no_docker
    )
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())