[xinao-core]
pg1-path=/var/lib/postgresql/data
pg1-user=temporal

[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full-type=count
repo1-retention-full=7
repo1-retention-archive-type=full
repo1-retention-archive=7
repo1-retention-history=30
repo1-bundle=y
compress-type=zst
process-max=2
start-fast=y
expire-auto=y
archive-async=n
log-level-console=info
log-level-file=off

[global:archive-push]
compress-level=3
log-level-console=off
log-level-stderr=error
